---
version: "2.1"
services:
  plex:
    #image: ghcr.io/linuxserver/plex
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    #environment:
    #  - PUID=1000
    #  - PGID=1000
    #  - VERSION=docker
    #  #- PLEX_CLAIM= #optional
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      #- PLEX_CLAIM="claim-YYYYYYYYY"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.1.75:32400/"
    volumes:
      - /Users/gini/codes/plex-data/library:/config
      - /Users/gini/codes/plex-data/tvseries:/tv
      - /Users/gini/codes/plex-data/movies:/movies
    restart: unless-stopped