---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    #network_mode: host
    ports:
      - "8085:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #claim-ixrZJEmAY62LwPU9r_x8 #optional
    volumes:
      - /Users/gini/codes/plex-data/library:/config
      - /Users/gini/codes/plex-data/tvseries:/tv
      - /Users/gini/codes/plex-data/movies:/movies
      - /Volumes/WD1T_DATA_1/Watch:/watch
    restart: unless-stopped